baseURL = "https://www.robert-sokolewicz.nl"

languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 50

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Roberts blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Home"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv"
      [[languages.en.menu.main]]
        identifier = "physics"
        name = "Physics"
        url = "/physics"
      [[languages.en.menu.main]]
        identifier = "Books"
        name = "Book Reviews"
        url = "/books"
      [[languages.en.menu.main]]
        identifier = "reading papers"
        name = "Reading Papers"
        url = "/reading_papers"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
        